export const LIST_LOADED = 'LIST_LOADED';
export const FILE_UPLOADED = 'FILE_UPLOADED';
export const FILE_SELECTED = 'FILE_SELECTED';
export const PROGRESS_CHANGE = 'PROGRESS_CHANGE';
export const MESSAGE_CHANGED = 'MESSAGE_CHANGED';
